# https://www.mkdocs.org/user-guide/configuration/
# https://www.mkdocs.org/user-guide/writing-your-docs/
# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/writing-your-docs/
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/styling-your-docs/
# https://example-mkdocs-basic.readthedocs.io/en/latest/
# https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml
# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# mkdocs.yml

site_name: "PSPreworkout PowerShell Module"
site_url: "https://day3bits.com/PSPreworkout"
repo_url: "https://github.com/SamErde/PSPreworkout"
repo_name: "PSPreworkout"
# edit_uri: edit/main/docs/
# edit_uri_template:
site_description: "PowerShell Preworkout: a mix of tools to help jump start your PowerShell session!" # meta tag to the generated HTML heade
site_author: "Sam Erde" # meta tag to the generated HTML header
copyright: "(c) 2024 Sam Erde."
# remote_branch: gh-deploy
# remote_name:
docs_dir: "docs"
# site_dir:
# extra_css:
# extra_javascript:
# markdown_extensions:
# Python Markdown
# - admonition
# - toc:
#     permalink: true
# code highlighting
# - pymdownx.highlight:
#     use_pygments: true
# - pymdownx.highlight:
#     anchor_linenums: true
# - pymdownx.inlinehilite
# - pymdownx.snippets
# - pymdownx.superfences

# extra_templates:
# extra:

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: en
  # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
  # favicon:
  # icon:
  #   repo:
  # font:
  #   text: Work Sans
  # logo:

nav:
  - Home: "index.md"
  - Customize:
      - Initialize-PSEnvironmentConfiguration: "Initialize-PSEnvironmentConfiguration.md"
      - Edit-WinGetSettings: "Edit-WinGetSettings.md"
      - Install-OhMyPosh: "Install-OhMyPosh.md"
      - Install-PowerShellISE: "Install-PowerShellISE.md"
      - Install-WinGet: "Install-WinGet.md"
      - Set-ConsoleFont" "Set-ConsoleFont.md"
  - Develop:
      - Get-TypeAccelerator: "Get-TypeAccelerator.md"
      - Get-LoadedAssembly: "Get-LoadedAssembly.md"
      - Show-LoadedAssembly: "Show-LoadedAssembly.md"
      - New-ScriptFromTemplate: "New-ScriptFromTemplate.md"
  - Daily Functions:
      - Get-EnvironmentVariable: "Get-EnvironmentVariable.md"
      - Set-EnvironmentVariable: "Set-EnvironmentVariable.md"
      - New-Credential: "New-Credential.md"
      - Test-IsElevated: "Test-IsElevated.md"
      - Update-AllTheThings: "Update-AllTheThings.md"
