name: Create External Help

on:
  workflow_run:
    types:
      - completed
    jobs:
      - 💾 Commit Changes

jobs:
  package_help:
    runs-on: ubuntu-latest
    steps:
      - name: 📖 Create and Package External PowerShell Help
        shell: pwsh
        run: |
          Copy-Item ".\src\Artifacts\en-US\PSPreworkout-help.xml" ".\src\Help\en-US"
          $params = @{
              CabFilesFolder  = ".\src\Help\en-US"
              LandingPagePath = ".\docs\PSPreworkout.md"
              OutputFolder    = ".\src\Help\en-US"
          }
          New-ExternalHelpCab @params

        # git-auto-commit-action only runs on Linux-based platforms.
      - name: 💾 Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Create and package external help.'
