name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # The branch you want to deploy from
    paths:  # Only deploy MkDocs when the contents of the docs folder change or when this workflow changes.
      - 'docs/**'
      - '.github/workflows/Deploy MkDocs.yml'
      - './mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build and deploy
        run: |
          mkdocs build
          mkdocs gh-deploy --force

      - name: Update Index and Readme Documentation
        shell: pwsh
        run: |
          $IndexTop = Get-Content -Path ./docs/index.md -TotalCount 42
          $ModuleContent = Get-Content -Path ./docs/PSPreworkout.md | Select-Object -Skip 12
          $CombinedContent = $IndexTop + $ModuleContent
          $CombinedContent | Set-Content -Path ./docs/index.md
          $ModuleContent = $ModuleContent.Replace( '](' , '](./docs/' )
          $CombinedContent = $IndexTop + $ModuleContent
          $CombinedContent | Set-Content -Path ./README.md
          # Copy-Item ./docs/index.md ./README.md

        # git-auto-commit-action only runs on Linux-based platforms.
      - name: Commit Changes to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Copy MkDocs index to README'
          file_pattern: 'docs/index.md README.md'
