name: Publish PowerShell Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:

    - name: Check Out Repository
      uses: actions/checkout@v4
    - name: Display the Path
      shell: pwsh
      run: echo ${env:PATH}
    - name: Display Version
      shell: pwsh
      run: $PSVersionTable
    - name: Publish to PowerShell Gallery
      run: |
        Publish-Module -Path '.\src\PSPreworkout' -NuGetApiKey ${{ secrets.POWERSHELLGALLERY_KEY }}
      env:
        PS_GALLERY_KEY: ${{ secrets.POWERSHELLGALLERY_KEY }}
