name: Publish PowerShell Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:

    - name: Publish to PowerShell Gallery
      run: |
        Publish-Module -Path '.\src\PSPreworkout' -NuGetApiKey ${{ secrets.POWERSHELLGALLERY_KEY }}
      env:
        PS_GALLERY_KEY: ${{ secrets.POWERSHELLGALLERY_KEY }}
