name: Publish to PowerShell Gallery
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Project Files
      uses: actions/checkout@v4
    - name: Publish PowerShell Module
      shell: pwsh
      run: |
        #./publish.ps1 -PSGalleryApiKey ${{ secrets.POWERSHELLGALLERY_PSPREWORKOUT }}
        # Publish-Module -Path ./src/PSPreworkout -NugetApiKey {{ secrets.POWERSHELLGALLERY_PSPREWORKOUT }}
        Publish-Module -Path ./scc/PSPreworkout -NugetApiKey {{ secrets.POWERSHELLGALLERY_PSPREWORKOUT }}
