name: Publish Module to PowerShell Gallery

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
#      - name: Publish Module to PowerShell Gallery
#        uses: pcgeek86/publish-powershell-module-action@v20
#        id: publish-module
#        with:
#          NuGetApiKey: ${{ secrets.POWERSHELLGALLERY_PSPREWORKOUT }}
      - name: Publish PowerShell Module
        shell: pwsh
        run: |
          Write-Output "$pwd`n$PSScriptRoot"
          Publish-Module -Path "$pwd/src/PSPreworkout" -NuGetApiKey ${{ secrets.POWERSHELLGALLERY_PSPREWORKOUT }}
